name: Weather API Scheduler

on:
  schedule:
    - cron: '0 */2 * * *' # This schedules the job to run every 2 hours. Adjust the cron expression as per your needs.
  workflow_dispatch:  # This line allows manual triggering

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.8

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install requests

    - name: Run Script
      run: python ./WeatherPing.py
      env:
        API_KEY: ${{ secrets.OPENWEATHERMAP_API_KEY }}
